### PR TITLE
Add support for Silverstripe 5

### LINKED ISSUE #60: Template customisation namespace is wrong
Docs advise using e.g. `templates/JonoM/BetterNavigator/Includes/ BetterNavigatorExtraContent.ss` but code calls `->renderWith('BetterNavigator\\BetterNavigator')`, so in fact if the templates are in a `JonoM` directory they get ignored.

### PR DESCRIPTION
**Pull request by chrispenny**
### Breaking change

Moved templates into `JonoM` namespace. Update `renderWith()` and `<% include %>` references.

Fixes #60
Closes #60

**Upgrade actions:** Developers will need to move any custom/overriding templates into a `JonoM` directory (matching what is documented in the `README`).

### Breaking change

`SilverStripeNavigator` has moved namespace in Silverstripe 5. With that being the case, I don't believe we can support Silverstripe 4 and 5 at the same time? (Though I will be happy to be wrong).

### `shouldDisplay()` cache change

The way that this cache was being set to a field seems to throw an error with Silverstripe 5:
```
ERROR [Warning]: Undefined array key "_betterNavigatorShouldDisplay"
IN GET /server-error
Line 220 in /var/www/mysite/www/vendor/silverstripe/framework/src/View/ViewableData.php
```

Using local/mem-cache on the Extension will achieve the same result.

## `BetterNavigator.ss` changes

In Silverstripe 5 there is now a configuration to allow/disallow trailing slashes. For the `Build databases` and `Dev menu` links, it's easier to use relative links, as we then don't need to bother with checking if trailing slashes were present or not.

Trailing slash change: https://github.com/silverstripe/silverstripe-framework/pull/10538

### CODE REVIEW

**Comment by jonom** [comment]
Thanks for working on this @chrispenny. If you have a sec while you're dealing with namespaces you might want to take a peek at [this issue](https://github.com/jonom/silverstripe-betternavigator/issues/60), otherwise I'll aim to do that before we bump the version on this module.

**Comment by chrispenny** [comment]
Thanks, @jonom! I'll have a look today :D

**Comment by chrispenny** [comment]
Looks to be working with the suggested namespace change.

Template for each include:
Screen Shot 2023-02-14 at 8 01 55 AM

New buttons added:
Screen Shot 2023-02-14 at 8 01 40 AM

**Comment by jonom** [comment]
Awesome, thanks @chrispenny! Have tagged [6.0.0-beta1](https://github.com/jonom/silverstripe-betternavigator/releases/tag/6.0.0-beta1) and created a [5 branch](https://github.com/jonom/silverstripe-betternavigator/tree/5).

**Pull request merged**
