### PR TITLE
Added i18n support for SS4

### PR DESCRIPTION
**Pull request by AndreasLang50**
This pull request adds i18n translation functionality, usable with `.yml` Files in the lang folder as usual.
I've already included the English and German translation files.

And while I was on it, I decided to add title attributes for the last links in the debugging section with the descriptions copied from the official SilverStripe Document.

Changelog:
- Replaced hard coded Text with translation Tags/Methods.
- Made very few adjustments in `BetterNavigatorExtension.php` to maintain functionality (A few styles broke).
- Added title attributes to the debug links (Copied Descriptions from the [URL Variable Tools](https://docs.silverstripe.org/en/4/developer_guides/debugging/url_variable_tools/) Document)

### CODE REVIEW

**Review by jonom — CHANGES_REQUESTED** [review]
Thanks so much @AndreasLang50! Will be great to have i18n in this module. I will take a closer look soon, but one thing that jumps out is that all of the translation entries should be fully namespaced. Currently 3 keys are under `JonoM\BetterNavigator\Extension\BetterNavigatorExtension` while the rest are simply under `BetterNavigator`. I'm happy for all of the keys to go under `JonoM\BetterNavigator:`, I don't think we need to be any more specific than that.

**Comment by AndreasLang50** [comment]
Yeah, you're right, I thought of it as the root scope, therefore not having any namespaces, but they do make a lot of sense.
I've now put all translations into `JonoM\BetterNavigator` as requested.

**Comment by AndreasLang50** [comment]
@jonom Any updates on this please? Thanks :)

**Comment by jonom** [comment]
@AndreasLang50 sorry for the delay on this! Have been super busy but it's on my to do list to check this, aiming to test and merge this week.

**Comment by AndreasLang50** [comment]
Alright, thx!

**Review by jonom — APPROVED** [review]

**Comment by jonom** [comment]
Great work @AndreasLang50, thank you! Sorry for the delay in reviewing. Merged and tagged a 5.1.0 release.

**Comment by AndreasLang50** [comment]
thanks :)

**Pull request merged**
