### PR TITLE
Conversion to a Vendor Module

### PR DESCRIPTION
**Pull request by UndefinedOffset**
This pull request converts the module to a vendor module which assists with compatibility for 4.1.0 (though it does work fine with 4.0).

### CODE REVIEW

**Comment by jonom** [comment]
Thanks @UndefinedOffset. Have been away for a while and don't have time to test this myself right now - I assume you've put this change through the paces?

**Comment by UndefinedOffset** [comment]
Yep also just verified it also works properly through composer using our fork as well. It's exposing the folders as expected and loading properly :)

**Comment by UndefinedOffset** [comment]
Found one issue, looking into will update when I have a fix shouldn't take long just wanted to alert before it's merged.

**Comment by UndefinedOffset** [comment]
And... addressed :) so it's good to go now

**Comment by jonom** [comment]
Thanks!

**Comment by adrexia** [comment]
Awesome! Any chance we could get a release tagged with this in it? :)

**Comment by jonom** [comment]
Oops! Yeah... I guess a minor release should do the trick for this change? It's backwards compatible right?

**Comment by adrexia** [comment]
From what I understand the `silverstripe-module` type was what kept it out of vendor in the first place. It looks like everyone else has been using minor releases, if that helps? And vendor modules work in 4.0 and 4.1 so it should be fine :)

**Comment by jonom** [comment]
Cool. Have tagged a 4.1 release.

**Pull request merged**
